server:
  error:
    include-stacktrace: never

spring:
  jpa:
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: 2b0dea8070dbe7
    password: 70d089c6b7d148
    properties:
      mail:
        transport:
          protocol: smtp
        debug: true
        smtp:
          auth: true
          starttls:
            mail: true

logging:
  level:
    root: INFO

jwt:
  secret: c2VjcmV0X2tleV9qd3RfdG9rZW5fWWZyNTZEcmZ2a8uGN2diczdHSGdiOGhCQmo4aEhqMDk3Qk5rajdSZ0xxYkZ5NzVEdmNhMGhiZnZSZ2FIZDM0RHNhcGpucQ==